##### *깃허브 파일 용량 문제로 몇몇 코드는 주석처리 하였습니다

### 파일 열기

In [23]:
import pandas as pd

df=pd.read_csv('행정구역_인구_출근발생량_전기차_충전소_앵커시설_완속.csv')
df.head()

       행정구역   총 인구수    총출근발생량  전기차 수  충전소 개수  앵커시설      완속
0       가평군   62389   20592.0    919   250.0     2   380.0
1   고양시 덕양구  493506  190060.0   5538   429.0    10  1856.0
2  고양시 일산동구  293740  108701.0   3296   452.0    12  1897.0
3  고양시 일산서구  284559  105587.0   3193   352.0     7  1708.0
4       과천시   84278   25846.0   1254    98.0     2   264.0

### 행정구역 컬럼 제외

In [2]:
col_names=['총 인구수', '총출근발생량', '전기차 수', '앵커시설', '충전소 개수', '완속']

In [3]:
x=df[col_names]
x

     총 인구수    총출근발생량  전기차 수  앵커시설  충전소 개수      완속
0    62389   20592.0    919     2   250.0   380.0
1   493506  190060.0   5538    10   429.0  1856.0
2   293740  108701.0   3296    12   452.0  1897.0
3   284559  105587.0   3193     7   352.0  1708.0
4    84278   25846.0   1254     2    98.0   264.0
5   278744  137485.0   2518    10   221.0  1100.0
6   392998  143245.0   3834     3   420.0  1409.0
7   186079   84273.0   1462     5   212.0   938.0
8   259307  134493.0   2260     5   232.0   894.0
9   485749  164278.0   8139    11   667.0  3500.0
10  684466  259228.0   7766    15   911.0  4681.0
11   87563   35637.0    966     3   129.0   414.0
12  228977  120264.0   1868     6   147.0   635.0
13  153830  120264.0   1255     0    73.0   178.0
14  392260  120264.0   3201    13   377.0  1593.0
15  471067  175293.0   6327     9   736.0  3523.0
16  237477  110612.0   3474     5   268.0  1167.0
17  209221  119894.0   3105     1   213.0   765.0
18  365041  161709.0   3849    10   355.0  1785.0
19  362095  154321.0   4074     9   499.0  2474.0
20  274538  116865.0   3089     8   212.0   832.0
21  195682   88934.0   2202     6   196.0   694.0
22  518844  250753.0   4055    11   602.0  2902.0
23  294787  182149.0   2919     9   383.0  1646.0
24  331013  160090.0   3278     5   167.0   594.0
25  191247   94750.0   2159     6   331.0  1081.0
26  317054  138134.0   2827    10   301.0  1365.0
27  229107  100753.0   2042     2   191.0   683.0
28  278546   93253.0   3135     4   374.0  1773.0
29  126129   26368.0   2228     1   195.0   309.0
30  114522   45690.0   1731     2   164.0   477.0
31   41081   13107.0    828     0    66.0    96.0
32  235681  120312.0   1919     6   248.0  1225.0
33  437307  159466.0   4979    13   641.0  3237.0
34  376250  113277.0   5239     8   628.0  2946.0
35  267936  114930.0   3731     5   323.0  1212.0
36  155740   62731.0   1919     3   208.0   768.0
37  461661  179439.0   3695    10   509.0  2260.0
38  221704  105797.0   2708     4   325.0  1161.0
39  505659  201565.0   5487    13   661.0  2693.0
40  593549  229128.0   5190    10   670.0  3761.0
41  142429   73416.0   1514     3   227.0   449.0
42  329827  104409.0   4871     8   348.0  2198.0
43  952194  425616.0   9780    15  1321.0  5613.0

### Standard Scaling

In [28]:
from sklearn.preprocessing import StandardScaler

# StandardScaler 객체 생성
scaler = StandardScaler()

# 데이터를 StandardScaler에 fitting하고 변환
scaled_data = scaler.fit_transform(x)

# 변환된 데이터 출력
x_scaled = pd.DataFrame(scaled_data, columns=col_names)
x_scaled

       총 인구수    총출근발생량     전기차 수      앵커시설    충전소 개수        완속
0  -1.411943 -1.500525 -1.276700 -1.177632 -0.499537 -0.996639
1   1.054133  0.836840  1.095350  0.777682  0.238339  0.192822
2  -0.088569 -0.285293 -0.056011  1.266510  0.333150  0.225863
3  -0.141086 -0.328243 -0.108906  0.044439 -0.079072  0.073554
4  -1.286733 -1.428060 -1.104663 -1.177632 -1.126114 -1.090120
5  -0.174349  0.111706 -0.455547  0.777682 -0.619082 -0.416414
6   0.479207  0.191150  0.220274 -0.933218  0.201239 -0.167401
7  -0.704411 -0.622213 -0.997847 -0.444390 -0.656182 -0.546965
8  -0.285532  0.070439 -0.588040 -0.444390 -0.573737 -0.582423
9   1.009761  0.481245  2.431072  1.022096  1.219426  1.517669
10  2.146462  1.790830  2.239521  1.999753  2.225246  2.469400
11 -1.267942 -1.293018 -1.252564 -0.933218 -0.998325 -0.969240
12 -0.459026 -0.125812 -0.789349 -0.199975 -0.924126 -0.791143
13 -0.888882 -0.125812 -1.104150 -1.666461 -1.229169 -1.159424
14  0.474986 -0.125812 -0.104798  1.510925  0.023984 -0.019121
15  0.925777  0.633168  1.500534  0.533268  1.503859  1.536204
16 -0.410404 -0.258936  0.035399 -0.444390 -0.425338 -0.362421
17 -0.572034 -0.130915 -0.154098 -1.422047 -0.652059 -0.686380
18  0.319287  0.445812  0.227978  0.777682 -0.066705  0.135606
19  0.302436  0.343914  0.343524  0.533268  0.526894  0.690849
20 -0.198408 -0.172692 -0.162314  0.288853 -0.656182 -0.632387
21 -0.649480 -0.557927 -0.617826 -0.199975 -0.722137 -0.743597
22  1.199071  1.673940  0.333767  1.022096  0.951482  1.035760
23 -0.082580  0.727728 -0.249616  0.533268  0.048717  0.023590
24  0.124640  0.423483 -0.065255 -0.444390 -0.841681 -0.824183
25 -0.674849 -0.477710 -0.639908 -0.199975 -0.165638 -0.431726
26  0.044792  0.120657 -0.296862  0.777682 -0.289305 -0.202859
27 -0.458282 -0.394915 -0.699993 -1.177632 -0.742748 -0.752461
28 -0.175481 -0.498358 -0.138691 -0.688804  0.011617  0.125935
29 -1.047337 -1.420860 -0.604474 -1.422047 -0.726259 -1.053856
30 -1.113731 -1.154364 -0.859704 -1.177632 -0.854048 -0.918470
31 -1.533829 -1.603760 -1.323432 -1.666461 -1.258025 -1.225506
32 -0.420678 -0.125150 -0.763158 -0.199975 -0.507782 -0.315681
33  0.732663  0.414876  0.808280  1.510925  1.112248  1.305726
34  0.383405 -0.222179  0.941801  0.288853  1.058660  1.071219
35 -0.236173 -0.199381  0.167380 -0.444390 -0.198616 -0.326157
36 -0.877956 -0.919328 -0.763158 -0.933218 -0.672670 -0.683962
37  0.871973  0.690351  0.148892  0.777682  0.568116  0.518393
38 -0.500629 -0.325346 -0.357974 -0.688804 -0.190371 -0.367256
39  1.123651  0.995521  1.069159  1.510925  1.194693  0.867334
40  1.626399  1.375680  0.916637  0.777682  1.231793  1.728001
41 -0.954098 -0.771957 -0.971143 -0.933218 -0.594348 -0.941034
42  0.117856 -0.344490  0.752817  0.288853 -0.095560  0.468429
43  3.677920  4.085714  3.273794  1.999753  3.915354  3.220469

### 상관계수 확인하기

In [5]:
import matplotlib.pyplot as plt
# 한글 폰트 설정
plt.rc('font', family='Malgun Gothic')  # Windows
# plt.rc('font', family='AppleGothic')  # macOS
plt.rcParams['axes.unicode_minus'] = False  # 마이너스 기호 깨짐 방지

In [1]:
# # 상관 계수 계산
# corr_matrix = x_scaled.corr()

# # 상관 계수 히트맵 시각화 (옵셔널)
# import seaborn as sns
# import matplotlib.pyplot as plt

# plt.figure(figsize=(12, 10))
# sns.heatmap(corr_matrix, annot=True, cmap='RdBu', vmin=-1, vmax=1)
# plt.title('Correlation Matrix')
# plt.show()

# # 예를 들어, 상위 5개 주요 컬럼 선택
# num_top_features = 6
# significant_columns = corr_matrix.abs().nlargest(num_top_features, '충전소 개수')['충전소 개수'].index.tolist()

# print("주요 컬럼:", significant_columns)

### 덴드로그램으로 군집 확인

In [2]:
# # 계층적 군집화
# from scipy.cluster.hierarchy import linkage, dendrogram, fcluster
# # linkage 함수를 사용하여 거리 행렬 생성
# Z = linkage(x_scaled, method='ward')

# # 덴드로그램 그리기
# plt.figure(figsize=(10, 5))
# dendrogram(Z)
# plt.title('Hierarchical Clustering Dendrogram')
# plt.xlabel('Data points')
# plt.ylabel('Distance')
# plt.show()

# # 거리 기준으로 군집 형성
# max_d = 8  # 군집 간 최대 거리 8로 설정
# clusters = fcluster(Z, max_d, criterion='distance')

# # 군집 결과를 데이터프레임에 추가
# data_with_clusters = pd.DataFrame(x_scaled, columns=col_names)
# data_with_clusters['Cluster'] = clusters

# # 각 군집별 데이터 출력
# for cluster_num in data_with_clusters['Cluster'].unique():
#     print(f"Cluster {cluster_num}:")
#     cluster_data = data_with_clusters[data_with_clusters['Cluster'] == cluster_num]
#     print(cluster_data)
#     print()
#     print(cluster_data.describe())
#     print()

### map으로 군집 시각화

In [30]:
new_df = x_scaled.copy()
new_df['행정구역'] = df['행정구역']
new_df['클러스터'] = clusters

In [32]:
new_df

       총 인구수    총출근발생량     전기차 수      앵커시설    충전소 개수        완속      행정구역  클러스터
0  -1.411943 -1.500525 -1.276700 -1.177632 -0.499537 -0.996639       가평군     3
1   1.054133  0.836840  1.095350  0.777682  0.238339  0.192822   고양시 덕양구     2
2  -0.088569 -0.285293 -0.056011  1.266510  0.333150  0.225863  고양시 일산동구     2
3  -0.141086 -0.328243 -0.108906  0.044439 -0.079072  0.073554  고양시 일산서구     3
4  -1.286733 -1.428060 -1.104663 -1.177632 -1.126114 -1.090120       과천시     3
5  -0.174349  0.111706 -0.455547  0.777682 -0.619082 -0.416414       광명시     2
6   0.479207  0.191150  0.220274 -0.933218  0.201239 -0.167401       광주시     3
7  -0.704411 -0.622213 -0.997847 -0.444390 -0.656182 -0.546965       구리시     3
8  -0.285532  0.070439 -0.588040 -0.444390 -0.573737 -0.582423       군포시     3
9   1.009761  0.481245  2.431072  1.022096  1.219426  1.517669       김포시     1
10  2.146462  1.790830  2.239521  1.999753  2.225246  2.469400      남양주시     1
11 -1.267942 -1.293018 -1.252564 -0.933218 -0.998325 -0.969240      동두천시     3
12 -0.459026 -0.125812 -0.789349 -0.199975 -0.924126 -0.791143   부천시 소사구     3
13 -0.888882 -0.125812 -1.104150 -1.666461 -1.229169 -1.159424   부천시 오정구     3
14  0.474986 -0.125812 -0.104798  1.510925  0.023984 -0.019121   부천시 원미구     2
15  0.925777  0.633168  1.500534  0.533268  1.503859  1.536204   성남시 분당구     1
16 -0.410404 -0.258936  0.035399 -0.444390 -0.425338 -0.362421   성남시 수정구     3
17 -0.572034 -0.130915 -0.154098 -1.422047 -0.652059 -0.686380   성남시 중원구     3
18  0.319287  0.445812  0.227978  0.777682 -0.066705  0.135606   수원시 권선구     2
19  0.302436  0.343914  0.343524  0.533268  0.526894  0.690849   수원시 영통구     2
20 -0.198408 -0.172692 -0.162314  0.288853 -0.656182 -0.632387   수원시 장안구     2
21 -0.649480 -0.557927 -0.617826 -0.199975 -0.722137 -0.743597   수원시 팔달구     3
22  1.199071  1.673940  0.333767  1.022096  0.951482  1.035760       시흥시     1
23 -0.082580  0.727728 -0.249616  0.533268  0.048717  0.023590   안산시 단원구     2
24  0.124640  0.423483 -0.065255 -0.444390 -0.841681 -0.824183   안산시 상록구     3
25 -0.674849 -0.477710 -0.639908 -0.199975 -0.165638 -0.431726       안성시     3
26  0.044792  0.120657 -0.296862  0.777682 -0.289305 -0.202859   안양시 동안구     2
27 -0.458282 -0.394915 -0.699993 -1.177632 -0.742748 -0.752461   안양시 만안구     3
28 -0.175481 -0.498358 -0.138691 -0.688804  0.011617  0.125935       양주시     3
29 -1.047337 -1.420860 -0.604474 -1.422047 -0.726259 -1.053856       양평군     3
30 -1.113731 -1.154364 -0.859704 -1.177632 -0.854048 -0.918470       여주시     3
31 -1.533829 -1.603760 -1.323432 -1.666461 -1.258025 -1.225506       연천군     3
32 -0.420678 -0.125150 -0.763158 -0.199975 -0.507782 -0.315681       오산시     3
33  0.732663  0.414876  0.808280  1.510925  1.112248  1.305726   용인시 기흥구     1
34  0.383405 -0.222179  0.941801  0.288853  1.058660  1.071219   용인시 수지구     2
35 -0.236173 -0.199381  0.167380 -0.444390 -0.198616 -0.326157   용인시 처인구     3
36 -0.877956 -0.919328 -0.763158 -0.933218 -0.672670 -0.683962       의왕시     3
37  0.871973  0.690351  0.148892  0.777682  0.568116  0.518393      의정부시     2
38 -0.500629 -0.325346 -0.357974 -0.688804 -0.190371 -0.367256       이천시     3
39  1.123651  0.995521  1.069159  1.510925  1.194693  0.867334       파주시     1
40  1.626399  1.375680  0.916637  0.777682  1.231793  1.728001       평택시     1
41 -0.954098 -0.771957 -0.971143 -0.933218 -0.594348 -0.941034       포천시     3
42  0.117856 -0.344490  0.752817  0.288853 -0.095560  0.468429       하남시     2
43  3.677920  4.085714  3.273794  1.999753  3.915354  3.220469       화성시     1

In [33]:
new_df['행정구역'] = new_df['행정구역'].str.replace(' ', '')
new_df

       총 인구수    총출근발생량     전기차 수      앵커시설    충전소 개수        완속     행정구역  클러스터
0  -1.411943 -1.500525 -1.276700 -1.177632 -0.499537 -0.996639      가평군     3
1   1.054133  0.836840  1.095350  0.777682  0.238339  0.192822   고양시덕양구     2
2  -0.088569 -0.285293 -0.056011  1.266510  0.333150  0.225863  고양시일산동구     2
3  -0.141086 -0.328243 -0.108906  0.044439 -0.079072  0.073554  고양시일산서구     3
4  -1.286733 -1.428060 -1.104663 -1.177632 -1.126114 -1.090120      과천시     3
5  -0.174349  0.111706 -0.455547  0.777682 -0.619082 -0.416414      광명시     2
6   0.479207  0.191150  0.220274 -0.933218  0.201239 -0.167401      광주시     3
7  -0.704411 -0.622213 -0.997847 -0.444390 -0.656182 -0.546965      구리시     3
8  -0.285532  0.070439 -0.588040 -0.444390 -0.573737 -0.582423      군포시     3
9   1.009761  0.481245  2.431072  1.022096  1.219426  1.517669      김포시     1
10  2.146462  1.790830  2.239521  1.999753  2.225246  2.469400     남양주시     1
11 -1.267942 -1.293018 -1.252564 -0.933218 -0.998325 -0.969240     동두천시     3
12 -0.459026 -0.125812 -0.789349 -0.199975 -0.924126 -0.791143   부천시소사구     3
13 -0.888882 -0.125812 -1.104150 -1.666461 -1.229169 -1.159424   부천시오정구     3
14  0.474986 -0.125812 -0.104798  1.510925  0.023984 -0.019121   부천시원미구     2
15  0.925777  0.633168  1.500534  0.533268  1.503859  1.536204   성남시분당구     1
16 -0.410404 -0.258936  0.035399 -0.444390 -0.425338 -0.362421   성남시수정구     3
17 -0.572034 -0.130915 -0.154098 -1.422047 -0.652059 -0.686380   성남시중원구     3
18  0.319287  0.445812  0.227978  0.777682 -0.066705  0.135606   수원시권선구     2
19  0.302436  0.343914  0.343524  0.533268  0.526894  0.690849   수원시영통구     2
20 -0.198408 -0.172692 -0.162314  0.288853 -0.656182 -0.632387   수원시장안구     2
21 -0.649480 -0.557927 -0.617826 -0.199975 -0.722137 -0.743597   수원시팔달구     3
22  1.199071  1.673940  0.333767  1.022096  0.951482  1.035760      시흥시     1
23 -0.082580  0.727728 -0.249616  0.533268  0.048717  0.023590   안산시단원구     2
24  0.124640  0.423483 -0.065255 -0.444390 -0.841681 -0.824183   안산시상록구     3
25 -0.674849 -0.477710 -0.639908 -0.199975 -0.165638 -0.431726      안성시     3
26  0.044792  0.120657 -0.296862  0.777682 -0.289305 -0.202859   안양시동안구     2
27 -0.458282 -0.394915 -0.699993 -1.177632 -0.742748 -0.752461   안양시만안구     3
28 -0.175481 -0.498358 -0.138691 -0.688804  0.011617  0.125935      양주시     3
29 -1.047337 -1.420860 -0.604474 -1.422047 -0.726259 -1.053856      양평군     3
30 -1.113731 -1.154364 -0.859704 -1.177632 -0.854048 -0.918470      여주시     3
31 -1.533829 -1.603760 -1.323432 -1.666461 -1.258025 -1.225506      연천군     3
32 -0.420678 -0.125150 -0.763158 -0.199975 -0.507782 -0.315681      오산시     3
33  0.732663  0.414876  0.808280  1.510925  1.112248  1.305726   용인시기흥구     1
34  0.383405 -0.222179  0.941801  0.288853  1.058660  1.071219   용인시수지구     2
35 -0.236173 -0.199381  0.167380 -0.444390 -0.198616 -0.326157   용인시처인구     3
36 -0.877956 -0.919328 -0.763158 -0.933218 -0.672670 -0.683962      의왕시     3
37  0.871973  0.690351  0.148892  0.777682  0.568116  0.518393     의정부시     2
38 -0.500629 -0.325346 -0.357974 -0.688804 -0.190371 -0.367256      이천시     3
39  1.123651  0.995521  1.069159  1.510925  1.194693  0.867334      파주시     1
40  1.626399  1.375680  0.916637  0.777682  1.231793  1.728001      평택시     1
41 -0.954098 -0.771957 -0.971143 -0.933218 -0.594348 -0.941034      포천시     3
42  0.117856 -0.344490  0.752817  0.288853 -0.095560  0.468429      하남시     2
43  3.677920  4.085714  3.273794  1.999753  3.915354  3.220469      화성시     1

In [35]:
new_df.groupby('클러스터').count()

      총 인구수  총출근발생량  전기차 수  앵커시설  충전소 개수  완속  행정구역
클러스터
1         8       8      8     8       8   8     8
2        12      12     12    12      12  12    12
3        24      24     24    24      24  24    24

In [ ]:
import json
import folium

with open('data/HangJeongDong_ver20230701.geojson', encoding='utf-8') as response:
    geo_json = json.load(response)

# 경기도 시군구 경계 정보를 가진 geo-json 파일 불러오기
# 경기도 행정구역 경계 지리 정보를 사용

geo_json

In [3]:
# # 경기도 지도 만들기
# g_map = folium.Map(location=[37.5502, 126.982], zoom_start=9)
# g_map
# # Choropleth 레이어를 만들고, 맵 m에 추가.

# folium.Choropleth(
#     geo_data=geo_json,
#     data=new_df,
#     columns=['행정구역', '클러스터'],
#     key_on="properties.sggnm",
#     nan_fill_color='white',
#     nan_fill_opacity=0.0,
#     fill_opacity=0.7, # 색 투명도
#     line_opacity=0.0, # 선 투명도
#     legend_name='군집', # 범례
#     fill_color= 'Set2'
# ).add_to(g_map)
# g_map